### PR TITLE
Feature/support test mode and customer ip validation

### PR DESCRIPTION
**Pull request by travism**
Here are the new fields. If you could review/accept these changes and republish the NPM that would be very helpful.

Best

### CODE REVIEW

**Comment by travism** [comment]
Your test probably fail because of Virtual Merchants expiring test credentials. Could you take a look at this in the near term? 

I'd like to simply use your version instead of using a fork and publishing a competing NPM but we are going to have to unblock ourselves in the next day or so.

Thanks

**Comment by kytwb** [comment]
@travism will merge and publish on Friday as I have to go through couple of things on all the [42-cent](https://github.com/continuous-software/42-cent) repos as well 👍

**Comment by travism** [comment]
Ok Friday will work. Thanks for taking the time.

**Comment by kytwb** [comment]
```
$ npm publish
+ virtualmerchant@1.2.1
```

**Pull request merged**
